# Generated by Django 3.2.20 on 2026-05-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='appointments.ward'),
        ),
        migrations.AddField(
            model_name='user',
            name='bed_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
